### ISSUE TITLE
[Missing Preheat Profiles] (An update to the preheat profiles)

### ISSUE THREAD

**Issue by H20Slicer** [Prussia3D/Marlin#3]
### Bug Description

Not really a bug. The configuration provided below has had it's preheat profiles updated to support not just PLA and PET but also PETG, PC, FLEX, ABS, ASA, HIPS, and Nylon. 

### My Configurations

[Updated Preheat Profiles.zip](https://github.com/Prussia3D/Marlin/files/5147207/Updated.Preheat.Profiles.zip)

### Steps to Reproduce

If you wish to add a material preheat profile not listed see the following.

Copy (see below) (ctrl c) under configuration.h line 1562, hit enter to move down a line then hit paste (ctrl v).
        #define PREHEAT_9_LABEL         "Nylon"
        #define PREHEAT_9_TEMP_HOTEND   260
        #define PREHEAT_9_TEMP_BED      110
        #define PREHEAT_9_FAN_SPEED     0 // Value from 0 to 255

Next you want to change the 9 to a 10, 11, 12, etc (depends on how many materials you want to add on all 4 lines after PREHEAT_   ex. ( #define PREHEAT_10). After that set your material name in place of Nylon and set your hotend and bed temps.

Ex 
        #define PREHEAT_10_LABEL         "PEI"
        #define PREHEAT_10_TEMP_HOTEND   380
        #define PREHEAT_10_TEMP_BED      120
        #define PREHEAT_10_FAN_SPEED     0 // Value from 0 to 255

**Comment by PaulGameDev** [comment]
Will add the missing Preheats in the next release, probably today.

**Comment by PaulGameDev** [comment]
Added with dc89388, closing...
